//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NaijaQuickFix.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Artisan
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Artisan()
        {
            this.Images = new HashSet<Image>();
        }
    
        public int Id { get; set; }
        public string CompanyName { get; set; }
        public string OfficeAddress { get; set; }
        public string Phone { get; set; }
        public string LGA { get; set; }
        public string State { get; set; }
        public string FullName { get; set; }
        public string Email { get; set; }
        public Nullable<System.DateTime> BirthDate { get; set; }
        public string NextOfKinPhoneNo { get; set; }
        public string HouseAddress { get; set; }
        public string NIN { get; set; }
        public int AssociationId { get; set; }
        public int GenderId { get; set; }
        public string JobDescription { get; set; }
        public System.DateTime DateRegistered { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<int> ProfessionId { get; set; }
        public Nullable<int> Status { get; set; }
    
        public virtual Profession Profession { get; set; }
        public virtual Association Association { get; set; }
        public virtual Gender Gender { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Image> Images { get; set; }
    }
}
